name: Build & Deploy to Cloud Run (OIDC, no secrets)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: {}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write     # requerido para OIDC
      contents: read
    env:
      PROJECT_ID: "gcp-mod1-lab-gobierno"
      REGION: "us-central1"
      REPO_AR: "apps"
      SERVICE: "hello-cr"
      # Ruta completa del provider WIF:
      WIF_PROVIDER: "projects/1027817535963/locations/global/workloadIdentityPools/github-pool/providers/github-provider"

    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud via OIDC (no secrets)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: gha-deployer@${{ env.PROJECT_ID }}.iam.gserviceaccount.com
          # Importante: NO 'credentials_json'

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Build image
        run: |
          docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_AR}/${SERVICE}:${GITHUB_SHA} .

      - name: Configure Artifact Registry auth
        run: |
          gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

      - name: Push image
        run: |
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_AR}/${SERVICE}:${GITHUB_SHA}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${SERVICE} \
            --image=${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_AR}/${SERVICE}:${GITHUB_SHA} \
            --region=${REGION} --allow-unauthenticated \
            --service-account=gha-deployer@${PROJECT_ID}.iam.gserviceaccount.com

